### ISSUE TITLE
Crash when trying to load with Quilt

### ISSUE THREAD

**Issue by Fusion-Flux** [MCRcortex/vulkanite#27]
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at net.minecraft.class_1008.method_4227(class_1008.java:142)
	at com.mojang.blaze3d.platform.GLX._init(GLX.java:106)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:852)
	at net.minecraft.class_310.<init>(class_310.java:505)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for lambda argument 0: class org.lwjgl.opengl.GLDebugMessageCallback is not convertible to interface org.lwjgl.system.Pointer
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:298)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:340)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
	... 18 more
	
Works fine when loading through fabric though so i will continue using that for now

**Comment by Fusion-Flux** [comment]
Aditionally i tested this on two machines 
My Windows laptop
My Linux home desktop
same crash

**Comment by Fusion-Flux** [comment]
Tested on quilt 0.21.0 and then tested on 0.20.2 quiltloader as ennui informed me 0.21.0 is a little sussy
