### ISSUE TITLE
me.cortex.vulkanite.lib.memory.VmaAllocator$SharedImageAllocation was not freed

### ISSUE THREAD

**Issue by 909oce** [MCRcortex/vulkanite#34]
Sodium 0.5.3 + Iris 1.6.9 + Vulkanite 0.0.4 pre-alpha

Game does not crash, however no shader will load and show the standard Iris can't load shader error in chat. This is the console log:

[16:14:10] [Cleaner-1/INFO]: [STDERR]: Object named: me.cortex.vulkanite.lib.memory.VmaAllocator$SharedImageAllocation was not freed, location at: 
[16:14:10] [Cleaner-1/INFO]: [STDERR]: java.lang.Throwable
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.base.TrackedResourceObject.register(TrackedResourceObject.java:28)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.base.TrackedResourceObject.<init>(TrackedResourceObject.java:9)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.memory.VmaAllocator$Allocation.<init>(VmaAllocator.java:279)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.memory.VmaAllocator$ImageAllocation.<init>(VmaAllocator.java:381)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.memory.VmaAllocator$SharedImageAllocation.<init>(VmaAllocator.java:397)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.memory.VmaAllocator.allocShared(VmaAllocator.java:253)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.memory.MemoryManager.createSharedImage(MemoryManager.java:219)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.memory.MemoryManager.createSharedImage(MemoryManager.java:183)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTarget.setupTextures(RenderTarget.java:574)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTarget.redirect$ibe000$vulkanite$redirectMain(RenderTarget.java:537)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTarget.<init>(RenderTarget.java:45)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTarget$Builder.build(RenderTarget.java:168)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTargets.create(RenderTargets.java:130)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTargets.getOrCreate(RenderTargets.java:120)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebuffer(RenderTargets.java:344)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTargets.createColorFramebufferWithDepth(RenderTargets.java:316)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTargets.createFullFramebuffer(RenderTargets.java:312)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTargets.createFramebufferWritingToMain(RenderTargets.java:244)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.rendertarget.RenderTargets.<init>(RenderTargets.java:65)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:237)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.Iris.createPipeline(Iris.java:661)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:35)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.Iris.reload(Iris.java:609)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:585)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$3(ShaderPackScreen.java:243)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_4185.method_25306(class_4185.java:94)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_4264.method_25348(class_4264.java:56)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_339.method_25402(class_339.java:189)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_4069.method_25402(class_4069.java:38)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:197)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:98)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:409)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:98)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:169)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:169)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:288)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1241)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:802)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:250)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[16:14:10] [Cleaner-1/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by TH3N3WN00B** [comment]
Same happens with Sodium 0.5.3 and Iris 1.6.10 in 1.20.2

https://mclo.gs/iNlm3CM

**Comment by CrabbyDisk** [comment]
I have encountered this problem and I currently don't know of a way to fix it, for now, vulkanite 0.0.3 with sodium 5.2 and iris 1.6.8 works on my system.
