### ISSUE TITLE
Mod crashes: Amd + Linux 

### ISSUE THREAD

**Issue by littleangryork** [MCRcortex/vulkanite#35]
I tried to install the mod, played with drivers and versions, but it didn’t work. At the initialization stage the game crashes. I'm testing on archlinux with amdvlk, mesa 23, amd-vulkan-prefixes drivers. Here's the crash report:
`
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-11-03 23:01:23
Description: Unexpected error

java.lang.AssertionError: : Initialization of an object could not be completed for implementation-specific reasons.
	at me.cortex.vulkanite.lib.other.VUtil._CHECK_(VUtil.java:83)
	at me.cortex.vulkanite.lib.other.VUtil._CHECK_(VUtil.java:78)
	at me.cortex.vulkanite.lib.base.initalizer.VInitializer.createDevice(VInitializer.java:106)
	at me.cortex.vulkanite.client.Vulkanite.createVulkanContext(Vulkanite.java:137)
	at me.cortex.vulkanite.client.Vulkanite.<init>(Vulkanite.java:55)
	at me.cortex.vulkanite.client.Vulkanite.<clinit>(Vulkanite.java:47)
	at net.minecraft.class_310.handler$beb000$vulkanite$onRenderTick(class_310.java:7998)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.cortex.vulkanite.lib.other.VUtil._CHECK_(VUtil.java:83)
	at me.cortex.vulkanite.lib.other.VUtil._CHECK_(VUtil.java:78)
	at me.cortex.vulkanite.lib.base.initalizer.VInitializer.createDevice(VInitializer.java:106)
	at me.cortex.vulkanite.client.Vulkanite.createVulkanContext(Vulkanite.java:137)
	at me.cortex.vulkanite.client.Vulkanite.<init>(Vulkanite.java:55)
	at me.cortex.vulkanite.client.Vulkanite.<clinit>(Vulkanite.java:47)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric, file/DefaultPBR.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.5.8-1-clear
	Java Version: 21, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 714962680 bytes (681 MiB) / 1358954496 bytes (1296 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 3.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Navi 24 [Radeon RX 6400/6500 XT/6500M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 4098.00
	Graphics card #0 deviceId: 0x743f
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 33389.93
	Virtual memory used (MB): 5267.32
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Fabric Mods: 
		fabric-api: Fabric API 0.89.3+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+0737cd8077
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.1+0889cb7877
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.21
		iris: Iris 1.6.8
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.1
		sodium: Sodium 0.5.2
		vulkanite: Vulkanite 0.0.3-pre-alpha
			org_joml_joml: joml 1.10.4
			org_lwjgl_lwjgl: lwjgl 3.3.1
			org_lwjgl_lwjgl-glfw: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-glfw_natives-linux: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-glfw_natives-windows: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-meshoptimizer: lwjgl-meshoptimizer 3.3.1
			org_lwjgl_lwjgl-meshoptimizer_natives-windows: lwjgl-meshoptimizer 3.3.1
			org_lwjgl_lwjgl-openal: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-openal_natives-linux: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-openal_natives-windows: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-shaderc: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-shaderc_natives-linux: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-shaderc_natives-windows: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-spvc: lwjgl-spvc 3.3.1
			org_lwjgl_lwjgl-spvc_natives-windows: lwjgl-spvc 3.3.1
			org_lwjgl_lwjgl-stb: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-stb_natives-linux: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-stb_natives-windows: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-vma: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vma_natives-linux: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vma_natives-windows: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vulkan: lwjgl-vulkan 3.3.1
			org_lwjgl_lwjgl_natives-linux: lwjgl 3.3.1
			org_lwjgl_lwjgl_natives-windows: lwjgl 3.3.1
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 6500 XT (navi24, LLVM 16.0.6, DRM 3.54, 6.5.8-1-clear) GL version 4.6 (Core Profile) Mesa 23.2.1-arch1.2, AMD
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/DefaultPBR.zip
	Current Language: en_us
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz
`

**Comment by sylv256** [comment]
Please use a pasting service such as https://mclo.gs/.

**Comment by littleangryork** [comment]
Okey: https://mclo.gs/iwi3tJS

**Comment by zERO123331** [comment]
is there a fix for this issue?

**Comment by PoorPocketsMcNewHold** [comment]
https://github.com/MCRcortex/vulkanite/issues/1 Seems that Linux support isn't there yet either way.

**Comment by MixedVictor** [comment]
I don't know but maybe using zink could fix the issue? Although I don't have a ray tracing capable GPU, I can launch using both MESA_LOADER_DRIVER_OVERRIDE=zink and RADV_PERFTEST=emulate_rt,rt environment variables, but the shaders doesn't work. Also to note I did modify the source code to fix a issue on Linux (I don't think its related to this as I only commented some lines) and added lwjgl-spvc-natives-linux.jar to Minecraft to fix #29.

**Comment by zERO123331** [comment]
@MixedVictor using zink doesnt fix my issue and using softare rt is kinda useless if the only point of the mod is that you can use hardware rt

**Comment by MixedVictor** [comment]
> @MixedVictor using zink doesnt fix my issue and using softare rt is kinda useless if the only point of the mod is that you can use hardware rt

Yeah I know, I was just curious about the mod.

**Comment by DexterHaxxor** [comment]
Using latest mod release from git, mesa-git and #44, I've been able to fix this issue and use shaders in-game.

**Comment by zERO123331** [comment]
@DexterHaxxor Thx I will try it tomorrow and tell u if it worked
