### ISSUE TITLE
[BUG]: Black Screen

### ISSUE THREAD

**Issue by Sirmanki69** [MCRcortex/vulkanite#43]
Here's a more detailed explanation

Turning on shaders "VulkaniteDemoPack-main" results in black screen everywhere in-game, besides GUI elements.
Nothing I tried could fix the issue, turning on fullscreen or messing with settings doesn't change anything.

Furthermore, shaders "wisdom-shaders-vulkanite-main" crash the game completely upon loading. 

I'm also using PBR resourcepacks, however, the same issue also persists without them.

===Pc Specs===
CPU: Ryzen 5 5600x
GPU: RTX 3060ti
RAM: 16GB 3200MHz
OS: Windows 10 home

Here's a piece of console output from Prism Launcher that are marked in red, that show up upon entering a world with shaders "VulkaniteDemoPack-main" enabled:

===================================================================================
```
[17:43:35] [Cleaner-0/INFO]: [STDERR]: java.lang.Throwable
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.base.TrackedResourceObject.register(TrackedResourceObject.java:28)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.base.TrackedResourceObject.<init>(TrackedResourceObject.java:9)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.cmd.VCmdBuff.<init>(VCmdBuff.java:18)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.cmd.VCommandPool.createCommandBuffers(VCommandPool.java:59)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.cmd.VCommandPool.createCommandBuffers(VCommandPool.java:43)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at me.cortex.vulkanite.lib.cmd.VCommandPool.createCommandBuffer(VCommandPool.java:39)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at me.cortex.vulkanite.client.rendering.VulkanPipeline.<init>(VulkanPipeline.java:97)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.handler$bdj000$vulkanite$injectRTShader(NewWorldRenderingPipeline.java:1366)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:549)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.coderbot.iris.Iris.createPipeline(Iris.java:661)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:35)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.coderbot.iris.Iris.onLoadingComplete(Iris.java:226)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.minecraft.class_442.handler$zmg000$iris$showSodiumIncompatScreen(class_442.java:566)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.minecraft.class_442.method_25426(class_442.java:156)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25423(class_437.java:297)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1507(class_310.java:1080)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.minecraft.class_310.method_51251(class_310.java:690)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:674)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:211)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
[17:43:35] [Cleaner-0/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
===================================================================================

Below is a crash report I received after turning on shaders "wisdom-shaders-vulkanite-main"

===================================================================================
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-02-05 17:47:28
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "me.cortex.vulkanite.client.rendering.VulkanPipeline.renderPostShadows(me.cortex.vulkanite.lib.memory.VGImage, net.minecraft.class_4184)" because "this.pipeline" is null
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.handler$bdj000$vulkanite$renderShadows(NewWorldRenderingPipeline.java:1372)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1040)
	at net.minecraft.class_761.handler$zll000$iris$renderTerrainShadows(class_761.java:6537)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.handler$bdj000$vulkanite$renderShadows(NewWorldRenderingPipeline.java:1372)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1040)
	at net.minecraft.class_761.handler$zll000$iris$renderTerrainShadows(class_761.java:6537)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['Sirmanki'/194, l='ClientLevel', x=-4.08, y=90.00, z=-9.85]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,79,-32), Section: (at 0,15,0 in 0,4,-2; chunk contains blocks 0,-64,-32 to 15,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 11317 game time, 11317 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Vanilla-PBR-1-3-2.zip, file/DefaultPBR.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.9, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2597540776 bytes (2477 MiB) / 4194304000 bytes (4000 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4629
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 35745.38
	Virtual memory used (MB): 19313.13
	Swap memory total (MB): 19456.00
	Swap memory used (MB): 105.76
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4000m -Xmx8000m
	Fabric Mods: 
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		iris: Iris 1.6.8
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		sodium: Sodium 0.5.2
		vulkanite: Vulkanite 0.0.3-pre-alpha
			org_joml_joml: joml 1.10.4
			org_lwjgl_lwjgl: lwjgl 3.3.1
			org_lwjgl_lwjgl-glfw: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-glfw_natives-linux: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-glfw_natives-windows: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-meshoptimizer: lwjgl-meshoptimizer 3.3.1
			org_lwjgl_lwjgl-meshoptimizer_natives-windows: lwjgl-meshoptimizer 3.3.1
			org_lwjgl_lwjgl-openal: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-openal_natives-linux: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-openal_natives-windows: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-shaderc: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-shaderc_natives-linux: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-shaderc_natives-windows: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-spvc: lwjgl-spvc 3.3.1
			org_lwjgl_lwjgl-spvc_natives-windows: lwjgl-spvc 3.3.1
			org_lwjgl_lwjgl-stb: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-stb_natives-linux: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-stb_natives-windows: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-vma: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vma_natives-linux: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vma_natives-windows: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vulkan: lwjgl-vulkan 3.3.1
			org_lwjgl_lwjgl_natives-linux: lwjgl 3.3.1
			org_lwjgl_lwjgl_natives-windows: lwjgl 3.3.1
	Loaded Shaderpack: wisdom-shaders-vulkanite-main
		Profile: Custom (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.29, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/Vanilla-PBR-1-3-2.zip (incompatible), file/DefaultPBR.zip
	Current Language: en_us
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Sirmanki'/194, l='ServerLevel[New World]', x=-4.08, y=90.00, z=-9.85]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```
===================================================================================

![image](https://github.com/MCRcortex/vulkanite/assets/159051574/3f06a589-bb8e-45dd-82a4-706fc00cbefb)
![image](https://github.com/MCRcortex/vulkanite/assets/159051574/0ea5fb50-8458-4151-9408-e40a4a01dd1e)

**Comment by RoverBot-Dev** [comment]
Giving 10 GB of ram to minecraft fixed the issues i was having
you could try increasing the amount of ram you give to minecraft
