### ISSUE TITLE
Crash: A device memory allocation has failed

### ISSUE THREAD

**Issue by isXander** [MCRcortex/vulkanite#7]
```
[23:11:56] [Render thread/ERROR]: Unreported exception thrown!
java.lang.AssertionError: Failed to allocate buffer: A device memory allocation has failed.
	at me.cortex.vulkanite.lib.other.VUtil._CHECK_(VUtil.java:83) ~[vulkanite-0.0.2-pre-alpha.jar:?]
	at me.cortex.vulkanite.lib.memory.VmaAllocator.alloc(VmaAllocator.java:83) ~[vulkanite-0.0.2-pre-alpha.jar:?]
	at me.cortex.vulkanite.lib.memory.VmaAllocator.alloc(VmaAllocator.java:99) ~[vulkanite-0.0.2-pre-alpha.jar:?]
	at me.cortex.vulkanite.lib.memory.MemoryManager.createBuffer(MemoryManager.java:140) ~[vulkanite-0.0.2-pre-alpha.jar:?]
	at me.cortex.vulkanite.acceleration.AccelerationBlasBuilder.enqueue(AccelerationBlasBuilder.java:355) ~[vulkanite-0.0.2-pre-alpha.jar:?]
	at me.cortex.vulkanite.acceleration.AccelerationManager.chunkBuilds(AccelerationManager.java:29) ~[vulkanite-0.0.2-pre-alpha.jar:?]
	at me.cortex.vulkanite.client.Vulkanite.upload(Vulkanite.java:62) ~[vulkanite-0.0.2-pre-alpha.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.handler$zkl000$vulkanite$processResults(RenderSectionManager.java:2196) ~[sodium-fabric-mc1.20.1-0.5.2.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.processChunkBuildResults(RenderSectionManager.java) ~[sodium-fabric
``` 
caused in-game (obviously)

I hope these log lines help: 
```
Mods:
  iris-mc1.20.1-1.6.8
  sodium-fabric-mc1.20.1-0.5.2
  vulkanite-0.0.2-pre-alpha

[23:10:59] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[23:10:59] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
[23:10:59] [Render thread/INFO]: OpenGL Version: 3.2.0 NVIDIA 537.13
[23:11:01] [Render thread/INFO]: [STDOUT]: NVIDIA GeForce RTX 2070 SUPER
[23:11:01] [Render thread/INFO]: [STDOUT]: Queue 0 has address 23f8d04c560
[23:11:01] [Render thread/INFO]: [STDOUT]: Queue 1 has address 23f8d04daf0

```

**Comment by MCRcortex** [comment]
You dont have ReBAR enabled, its hitting the mapping limit of 256 mb, you can run at a lower render distance for a temporary solution

**Comment by MCRcortex** [comment]
fixed in https://github.com/MCRcortex/vulkanite/commit/5a18eebc1d9b886839f84fb549db82290b161bd7
